spring.application.name=retailapp
logging.level.org.springframework=info
logging.level.com.preethisri=DEBUG

#db property
spring.datasource.url=jdbc:mysql://localhost:3308/retail
spring.datasource.username=retail-admin
spring.datasource.password=retail

#entity changes to pull in to db
spring.jpa.hibernate.ddl-auto=create

#data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#print sql query in colsole
spring.jpa.show-sql=true